#!/usr/bin/env python3
"""
Assemble the directory Cloudflare serves.

    python3 scripts/build_site.py   ->   site/

The repository holds things that must never reach a public URL: the ministry's
source workbooks, the brand guidelines PDF, the framework PDF, the parsers. So
the deploy target is an allow-list — this script copies the files the browser
actually requests and nothing else — rather than the repository root with an
ignore-list, where a file added later would be published by default.

On top of copying it does four things the source files cannot do for themselves,
all driven by site.config.json:

  * stamps the absolute site URL into canonical / og:url / og:image, which must
    be absolute and therefore cannot live in a file that also opens from disk;
  * injects the Cloudflare Web Analytics beacon, or leaves it out entirely when
    no token is configured, rather than shipping a broken one;
  * writes robots.txt and sitemap.xml;
  * writes _headers, so repeat visits revalidate instead of re-downloading.

The result is committed, because the Cloudflare build runs `wrangler deploy`
directly and does not run this script. Re-run it after any change to the pages,
assets or parsed data, and commit what changes.
"""

import json
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
CONFIG = ROOT / "site.config.json"

# Every file the browser requests, and only those. Paths are relative to the
# repository root and keep their layout inside site/.
PUBLISHED = [
    "index.html",
    "privacy.html",
    "terms.html",
    "404.html",
    "assets/brand.css",
    "assets/page.css",
    "assets/echarts.min.js",
    # Built from ui/ by scripts/build_ui.mjs and committed, same as ECharts.
    "assets/reactbits.js",
    "assets/reactbits.css",
    "assets/mim-logo-primary.svg",
    "assets/mim-emblem.svg",
    "assets/favicon.ico",
    "assets/icon-180.png",
    "assets/icon-512.png",
    "assets/og-image.png",
    "data/dashboard-data.js",
]

# Pages that belong in the sitemap, with their change frequency.
SITEMAP = [("", "monthly", "1.0"), ("privacy.html", "yearly", "0.3"),
           ("terms.html", "yearly", "0.3")]

# Nothing matching these may appear under site/, whatever the list above says.
FORBIDDEN_SUFFIXES = {".xlsx", ".xls", ".pdf", ".py", ".json", ".md"}

URL_TOKEN = "__SITE_URL__"

# Cloudflare Web Analytics. `defer` so it never blocks the first paint, and it
# is the only third-party request the page makes.
BEACON = ('<script defer src="https://static.cloudflareinsights.com/beacon.min.js" '
          "data-cf-beacon='{{\"token\": \"{token}\"}}'></script>\n")

HEADERS = """\
# Generated by scripts/build_site.py — edit that, not this.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: geolocation=(), microphone=(), camera=(), interest-cohort=()

# Vendored libraries and artwork: change rarely, and a stale copy is only ever
# a revalidation away. This is the repeat-visit win — ECharts and the React
# Bits bundle are the two large ones, and neither moves between deploys.
/assets/*
  Cache-Control: public, max-age=604800

# Regenerated whenever the sources are reparsed, so a shorter leash.
/data/*
  Cache-Control: public, max-age=3600

# The pages themselves must never be served stale: they carry the routing.
/*.html
  Cache-Control: public, max-age=0, must-revalidate
"""


def load_config():
    if not CONFIG.exists():
        sys.exit(f"missing {CONFIG.name}")
    cfg = json.loads(CONFIG.read_text(encoding="utf-8"))
    url = str(cfg.get("site_url", "")).rstrip("/")
    if not url.startswith("https://"):
        sys.exit("site_url must be an absolute https:// URL with no trailing slash")
    return url, str(cfg.get("cf_beacon_token", "")).strip(), bool(cfg.get("indexable"))


def write_robots(url, indexable):
    if indexable:
        body = ("User-agent: *\nAllow: /\n\n"
                f"Sitemap: {url}/sitemap.xml\n")
    else:
        body = "User-agent: *\nDisallow: /\n"
    (SITE / "robots.txt").write_text(body, encoding="utf-8")


def write_sitemap(url):
    today = date.today().isoformat()
    rows = "".join(
        f"  <url>\n    <loc>{url}/{path}</loc>\n"
        f"    <lastmod>{today}</lastmod>\n"
        f"    <changefreq>{freq}</changefreq>\n"
        f"    <priority>{pri}</priority>\n  </url>\n"
        for path, freq, pri in SITEMAP)
    (SITE / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{rows}</urlset>\n", encoding="utf-8")


def main():
    url, token, indexable = load_config()

    missing = [p for p in PUBLISHED if not (ROOT / p).exists()]
    if missing:
        sys.exit("missing source file(s): " + ", ".join(missing))

    if SITE.exists():
        shutil.rmtree(SITE)
    for rel in PUBLISHED:
        dest = SITE / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / rel, dest)

    # ---- stamp the pages ---------------------------------------------------
    for rel in [p for p in PUBLISHED if p.endswith(".html")]:
        page = SITE / rel
        html = page.read_text(encoding="utf-8")
        html = html.replace(URL_TOKEN, url)
        if token:
            html = html.replace("</body>", BEACON.format(token=token) + "</body>", 1)
        if not indexable and '<meta name="robots"' not in html:
            html = html.replace("<head>", '<head>\n<meta name="robots" content="noindex">', 1)
        page.write_text(html, encoding="utf-8")

    if URL_TOKEN in (SITE / "index.html").read_text(encoding="utf-8"):
        sys.exit(f"{URL_TOKEN} survived substitution in index.html")

    write_robots(url, indexable)
    write_sitemap(url)
    (SITE / "_headers").write_text(HEADERS, encoding="utf-8")

    # ---- guards ------------------------------------------------------------
    written = sorted(p for p in SITE.rglob("*") if p.is_file())
    leaked = [p for p in written if p.suffix.lower() in FORBIDDEN_SUFFIXES]
    if leaked:
        sys.exit("refusing to publish: " + ", ".join(
            str(p.relative_to(ROOT)) for p in leaked))

    generated = {"robots.txt", "sitemap.xml", "_headers"}
    unexpected = {str(p.relative_to(SITE)) for p in written} - set(PUBLISHED) - generated
    if unexpected:
        sys.exit("unexpected file(s) in site/: " + ", ".join(sorted(unexpected)))

    # ---- report ------------------------------------------------------------
    total = sum(p.stat().st_size for p in written)
    print(f"site/  {len(written)} files, {total:,} bytes")
    print(f"  url        {url}")
    print(f"  indexable  {indexable}")
    print(f"  analytics  {'beacon injected' if token else 'NOT injected (no token)'}")

    warnings = []
    if not token:
        warnings.append(
            "cf_beacon_token is empty, so no analytics runs — but privacy.html "
            "tells visitors that analytics is used. Set the token, or edit that "
            "page, before launch.")
    for rel in ("privacy.html", "terms.html"):
        if "placeholder" in (SITE / rel).read_text(encoding="utf-8"):
            warnings.append(f"{rel} still contains unfilled placeholder blocks.")
    for w in warnings:
        print(f"  WARNING: {w}")


if __name__ == "__main__":
    main()
