#!/usr/bin/env node
/**
 * Bundle the React Bits interface layer into the two files the page loads.
 *
 *     npm install && npm run build     ->   assets/reactbits.js
 *                                           assets/reactbits.css
 *
 * The dashboard is a static site: Cloudflare serves the repository, there is
 * no build step in the deploy, and index.html has to keep working when it is
 * opened straight off a disk. So the bundle is produced here and committed,
 * exactly as assets/echarts.min.js already is. node_modules is not committed
 * and is not needed to serve the site — only to rebuild this pair of files.
 *
 * Re-run after any change under ui/, and commit what changes.
 */

import { build } from 'esbuild';
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_JS = join(ROOT, 'assets', 'reactbits.js');
const OUT_CSS = join(ROOT, 'assets', 'reactbits.css');

/* Kept at the head of both outputs. The vendored components are MIT with a
 * Commons Clause, and that notice has to travel with the copies. */
const BANNER = [
  '/*! Interface layer for the MIM graduates dashboard.',
  ' *  Built by scripts/build_ui.mjs from ui/ — do not edit this file.',
  ' *',
  ' *  Bundles React 18 and components from React Bits (https://reactbits.dev),',
  ' *  Copyright (c) David Haz, MIT + Commons Clause — see ui/reactbits/LICENSE.md.',
  ' *  Also bundles GSAP (https://gsap.com), Motion (https://motion.dev) and',
  ' *  OGL (https://github.com/oframe/ogl), each under its own licence.',
  ' */'
].join('\n');

const result = await build({
  entryPoints: [join(ROOT, 'ui', 'index.jsx')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2019'],
  jsx: 'automatic',
  loader: { '.js': 'jsx' },
  define: { 'process.env.NODE_ENV': '"production"' },
  outfile: OUT_JS,
  metafile: true,
  legalComments: 'none',
  banner: { js: BANNER, css: BANNER }
});

/* esbuild names the stylesheet after the entry point; the page asks for
 * reactbits.css, so the two are reconciled here rather than in the markup. */
const emitted = Object.keys(result.metafile.outputs);
const cssOut = emitted.find(f => f.endsWith('.css'));
if (cssOut) {
  const abs = join(ROOT, cssOut);
  if (abs !== OUT_CSS) {
    writeFileSync(OUT_CSS, readFileSync(abs));
  }
}

for (const f of [OUT_JS, OUT_CSS]) {
  const size = statSync(f).size;
  console.log(`wrote ${relative(ROOT, f)}  (${size.toLocaleString('en-US')} bytes)`);
}
